#!/bin/bash
set -e

cd platform/postgres
cat > .env <<EOF
POSTGRES_DB=${GLOBAL_POSTGRES_DB}
POSTGRES_USER=${GLOBAL_POSTGRES_USER}
POSTGRES_PASSWORD=${GLOBAL_POSTGRES_PASSWORD}
PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
OCI_BUCKET=nexahome-backups
OCI_PREFIX=postgres
EOF
docker compose pull
docker compose up -d

cd ../keycloak
cat > .env <<EOF
KEYCLOAK_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
OCI_BUCKET=nexahome-backups
OCI_PREFIX=keycloak
EOF
docker compose pull
docker compose up -d

cd ../n8n
cat > .env <<EOF
N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
POSTGRES_DB=${POSTGRES_DB_N8N}
POSTGRES_USER=${POSTGRES_USER_N8N}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD_N8N}
EOF
docker compose pull
docker compose up -d
